DELIMITER $$
USE work $$

DROP PROCEDURE IF EXISTS REP_POPULAR_OPERATIONS $$
CREATE PROCEDURE REP_POPULAR_OPERATIONS
(
  IN iDATETIME_FROM DATETIME,
  IN iDATETIME_TO DATETIME
)
REP_POPULAR_OPERATIONS:BEGIN

  DROP TEMPORARY TABLE IF EXISTS tt_prepare;
  CREATE TEMPORARY TABLE tt_prepare AS
  SELECT O.ID_TYPE_OPER,
         OT.NAME_OPER,
         COUNT(O.ID_TYPE_OPER) AS CNT
  FROM work.operations   O
  JOIN work.type_opers  OT ON OT.ID_TYPE_OPER = O.ID_TYPE_OPER
  WHERE O.DT BETWEEN iDATETIME_FROM AND iDATETIME_TO
  GROUP BY O.ID_TYPE_OPER
  ;
  CREATE INDEX IDX_tt_prepare ON tt_prepare (CNT);

  SET @NPP=0;
  DROP TEMPORARY TABLE IF EXISTS tt_report;
  CREATE TEMPORARY TABLE tt_report AS
  SELECT @NPP:=@NPP+1 AS NPP,
         T.NAME_OPER,
         T.CNT
  FROM tt_prepare T
  ORDER BY T.CNT DESC, T.NAME_OPER;

  SELECT 'Popularity',
         'Operation type',
         'Number of operations'
  UNION ALL
  SELECT T.NPP,
         T.NAME_OPER,
         T.CNT
  FROM tt_report T;

END $$

-- CALL REP_POPULAR_OPERATIONS(
-- '2019-06-01 14:00:00',
-- '2019-06-05 14:00:00'
-- ) $$

