DELIMITER $$
USE work $$

DROP PROCEDURE IF EXISTS REP_USER_OPERATIONS $$
CREATE PROCEDURE REP_USER_OPERATIONS
(
  IN iID_USER INT,
  IN iDATETIME_FROM DATETIME,
  IN iDATETIME_TO DATETIME
)
REP_USER_OPERATIONS:BEGIN


END $$

-- CALL REP_USER_OPERATIONS(
-- 1,
-- '2019-06-01 14:00:00',
-- '2019-06-05 14:00:00'
-- ) $$

